import { getSession } from "next-auth/react";
import Head from "next/head";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Modal from "../components/Modal";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import { db } from "../firebase";
export default function Home({ session, posts }) {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Instagram-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Feed */}
      <Feed posts={posts} />
      {/* Modal */}
      <Modal />
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  const qu = query(collection(db, "posts"), orderBy("timestamp", "desc"));
  const p = await getDocs(qu);

  const posts = p.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }));

  return {
    props: { session, posts }, // will be passed to the page component as props
  };
}
